{{- if .Values.routing.enabled }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "bootbase-wordpress.fullname" . }}-cert
  labels:
    {{- if .Values.wordpress.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.wordpress.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.wordpress.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.wordpress.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: istio-system
spec:
  secretName: {{ include "bootbase-wordpress.fullname" . }}-tls
  subject:
    organizations:
      - Bootbase BVBA
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Values.routing.domain }}
    - www.{{ .Values.routing.domain }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod

{{- end }}
