{{- if .Values.routing.enabled }}

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: istio-system
  name: {{ include "bootbase-wordpress.fullname" . }}-gateway
  labels:
    {{- if .Values.wordpress.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.wordpress.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.wordpress.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.wordpress.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.routing.domain }}
        - www.{{ .Values.routing.domain }}
      tls:
        mode: SIMPLE
        credentialName: {{ include "bootbase-wordpress.fullname" . }}-tls

{{- end }}
